apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2a-demo-server
  namespace: kagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2a-demo-server
  template:
    metadata:
      labels:
        app: a2a-demo-server
    spec:
      containers:
        - name: agent
          image: belskiiartem/mock-agent:v0.0.1
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: Authorization
            - name: PHOENIX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: phoenix-api-key
                  key: Authorization
            - name: "PHOENIX_ENDPOINT"
              value: "http://phoenix-svc.phoenix.svc.cluster.local:6006"
            - name: "PHOENIX_COLLECTOR_ENDPOINT"
              value: "http://phoenix-svc.phoenix.svc.cluster.local:6006"              
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://phoenix-svc.phoenix.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf

---
apiVersion: v1
kind: Service
metadata:
  name: a2a-demo-server
  namespace: kagent
spec:
  selector:
    app: a2a-demo-server
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: a2a-demo-server
  namespace: kagent
spec:
  type: Declarative
  description: Server agent (provides capabilities)

  declarative:
    modelConfig: default-model-config